# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ledger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cledger.proto\"X\n\x12TransactionRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"&\n\x13TransactionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"Q\n\x0bLedgerEntry\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"+\n\nLedgerData\x12\x1d\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0c.LedgerEntry\"\x07\n\x05\x45mpty2q\n\rLedgerService\x12>\n\x11RecordTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponse\x12 \n\tGetLedger\x12\x06.Empty\x1a\x0b.LedgerDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=16
  _globals['_TRANSACTIONREQUEST']._serialized_end=104
  _globals['_TRANSACTIONRESPONSE']._serialized_start=106
  _globals['_TRANSACTIONRESPONSE']._serialized_end=144
  _globals['_LEDGERENTRY']._serialized_start=146
  _globals['_LEDGERENTRY']._serialized_end=227
  _globals['_LEDGERDATA']._serialized_start=229
  _globals['_LEDGERDATA']._serialized_end=272
  _globals['_EMPTY']._serialized_start=274
  _globals['_EMPTY']._serialized_end=281
  _globals['_LEDGERSERVICE']._serialized_start=283
  _globals['_LEDGERSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)

